services:
  vcclient:
    image: dannadori/vcclient:20230826_211406
    volumes:
      - ./model_dir:/voice-changer/server/model_dir
      - ./pretrain:/voice-changer/server/pretrain
    ports:
      - 18888:18888
    environment:
      EX_IP: "127.0.0.1"
      EX_PORT: "18888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    privileged: true
    entrypoint:
      - /bin/bash
      - exec.sh
      - -p 18888
      - --https false
      - --content_vec_500 pretrain/checkpoint_best_legacy_500.pt
      - --content_vec_500_onnx pretrain/content_vec_500.onnx
      - --content_vec_500_onnx_on true
      - --hubert_base pretrain/hubert_base.pt
      - --hubert_base_jp pretrain/rinna_hubert_base_jp.pt
      - --hubert_soft pretrain/hubert/hubert-soft-0d54a1f4.pt
      - --nsf_hifigan pretrain/nsf_hifigan/model
      - --crepe_onnx_full pretrain/crepe_onnx_full.onnx
      - --crepe_onnx_tiny pretrain/crepe_onnx_tiny.onnx
      - --rmvpe pretrain/rmvpe.pt
      - --model_dir model_dir
      - --samples samples.json
